package all

import (
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/clone"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/converter"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/date"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/dedup"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/defaults"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/enum"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/execd"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/filepath"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/ifname"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/override"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/parser"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/pivot"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/port_name"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/printer"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/regex"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/rename"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/reverse_dns"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/s2geo"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/starlark"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/strings"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/tag_limit"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/template"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/topk"
	_ "github.com/pmalek-sumo/telegraf/plugins/processors/unpivot"
)
